# Generated by Django 5.0.2 on 2024-02-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=25)),
                ('bookname', models.CharField(max_length=30)),
                ('bookid', models.IntegerField()),
                ('pic', models.FileField(help_text='Upload photo in 50 kb', upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
            ],
        ),
    ]
